### ISSUE TITLE
Support desktop execution of unit tests

### ISSUE THREAD

**Issue by gvwilson** [datacamp/shellwhat#27]
Running `python -m pytest` in the root directory of `shellwhat` on a Mac produces:

```
subprocess.CalledProcessError: Command '['python2', '-m', 'osh', 'echo a b c;']' returned non-zero exit status 1.
```

Variations on this invocation produce similar results. When debugging `shellwhat_ext` SCTs, I would really like to be able to run their unit tests (and those for `shellwhat, naturally) native in my desktop.

**Comment by machow** [comment]
@gvwilson there are two issues here,

1. the `osh` parser is needed to run some of the unit tests
2. an error is raised if it's unavailable

I'll.. 

1. mark tests that require the parser, so they can be skipped if it's unavailable
2. add clear instructions on how to install the parser via docker (since it is not easy to do on mac)
3. make it easier to disable parsing
