### ISSUE TITLE
repl.run_command should NOT echo commands to the shell

### ISSUE THREAD

**Issue by gvwilson** [datacamp/shellwhat#30]
Learners are finding it very confusing that the pre-exercise commands executed via `repl.run_command` are echoed to their terminal.  I can fake my way around this by using `repl.run_command('clear')` inside each pre block.

**Comment by machow** [comment]
Sorry I completely missed this issue. Running `clear` seems like a reasonable solution, since this is exactly how the backend itself has to hide things ([see these lines](https://github.com/datacamp/shellbackend/blob/master/shellbackend/kernel.py#L170-L173)). I'll open an issue there to add a `echo` flag to `run_command`.
