### ISSUE TITLE
test_output_contains does not include errors

### ISSUE THREAD

**Issue by filipsch** [datacamp/shellwhat#35]
See the last lines of [this file](https://github.com/datacamp/courses-conda-essentials/blob/master/chapter4.md); in the exercise, we want to check whether a certain command produces the correct error. It seems that this is not possible through `test_output_contains()`. I'm suspecting that is because the error stream is not captured in the `stu_output` field of the `State`. Requires some more investigation, just wanted a placeholder. Not urgent.

**Comment by machow** [comment]
@filipsch the output is not stdout or stderr per se, but all terminal output. When you type something into your bash terminal on your laptop..

* you are using a terminal that takes input and gives out put
* the terminal is running a shell (bash), that it gives input / gets output from

When you see something in the terminal, you might know that it's stdin / stderr, but the terminal doesn't know--because that's the job of the shell process. The terminal just knows that it is output.

**How to check for an error**

The most reliable way to check for an error is to run a shell command, and see if it returns an error (that is, `echo $?` after the command is run). This is what the SCT [`test_expr_error`](https://github.com/datacamp/shellwhat/blob/master/shellwhat/checks.py#L122-L124) does. afaik there is no concept of stderr in a terminal.

see [what is a pseudoterminal](http://ptyprocess.readthedocs.io/en/latest/)
[similar issue brought up by greg](https://github.com/datacamp/learn-bugs/issues/62#issuecomment-349703964)

**Comment by filipsch** [comment]
@machow thanks for context, i'm pretty new to this stuff!

**Comment by machow** [comment]
@filipsch it's a pretty gnarly issue--here's an issue with some examples of where separating stdout from stderr were mentioned: https://github.com/datacamp/learn-bugs/issues/50

One mentioned is that for something with a progress bar, the output will be a cryptic mix symbols

**Comment by filipsch** [comment]
Irrelevant.
